= Vert.x Camel Bridge
:toc: left

Apache Camel (http://camel.apache.org) is an open source Java framework that focuses on making integration easier
and more accessible to developers.

This bridge lets Vert.x applications interact with Camel endpoints:

* the application can send messages to Camel.
* the application can receive message from Camel.

The bridge relies on the Vert.x event bus and associate an event bus address to a Camel endpoint.

CAUTION: This component is not _polyglot_ as it requires some classes from Camel that can only be used in Java.

== Using vertx-camel-bridge

To use the Vert.x Camel Bridge, add the following dependency to the _dependencies_ section of your
build descriptor:

* Maven (in your `pom.xml`):

[source,xml,subs="+attributes"]
----
<dependency>
  <groupId>io.vertx</groupId>
  <artifactId>vertx-camel-bridge</artifactId>
  <version>3.5.0.Beta1</version>
</dependency>
----

* Gradle (in your `build.gradle` file):

[source,groovy,subs="+attributes"]
----
compile 'io.vertx:vertx-camel-bridge:3.5.0.Beta1'
----

== Bridge configuration

Before being used, the bridge needs to be configured and started:

[source,kotlin]
----
var camel = org.apache.camel.impl.DefaultCamelContext()
io.vertx.camel.CamelBridge.create(vertx, io.vertx.camel.CamelBridgeOptions(camel).addInboundMapping(io.vertx.camel.InboundMapping.fromCamel("direct:stuff").toVertx("eventbus-address")).addOutboundMapping(io.vertx.camel.OutboundMapping.fromVertx("eventbus-address").toCamel("stream:out"))).start()

----

The bridge requires a `CamelContext`. It will find the endpoint from the context. The bridge needs to be started
before being used. Be aware the the `start` method is asynchronous. You can use
`link:../../apidocs/io/vertx/camel/CamelBridge.html#start-io.vertx.core.Handler-[start]` to be notified when the bridge has been started.



=== Inbound mapping

Inbound mapping associates a Camel endpoint to an event bus address. Messages received on this endpoint are
transformed to event bus messages.

[source,kotlin]
----
var endpoint = camel.getEndpoint("direct:foo")

io.vertx.camel.CamelBridge.create(vertx, io.vertx.camel.CamelBridgeOptions(camel).addInboundMapping(io.vertx.camel.InboundMapping.fromCamel("direct:stuff").toVertx("eventbus-address")).addInboundMapping(io.vertx.camel.InboundMapping.fromCamel(endpoint).toVertx("eventbus-address")).addInboundMapping(io.vertx.camel.InboundMapping.fromCamel(endpoint).toVertx("eventbus-address").withoutHeadersCopy()).addInboundMapping(io.vertx.camel.InboundMapping.fromCamel(endpoint).toVertx("eventbus-address").usePublish()).addInboundMapping(io.vertx.camel.InboundMapping.fromCamel(endpoint).toVertx("eventbus-address").withBodyType(String.`class`)))

----

The snippet above shows different ways to configure an inbound mapping:

* you can configure the Camel endpoint either using the `Endpoint` object or its uri
* you can disables the header copy (Camel message headers are copied to the event bus message)
* you can uses `publish` instead of `send` to broadcast the message to all event bus consumers
* you can configures the type of the event bus message body. If not set it uses the Camel message payload. If
sets, it looks in the Camel context for a converter between the Camel message payload and the desired type.

_Note_: `org.fusesource.hawtbuf.Buffer` are automatically converted to `link:../../apidocs/io/vertx/core/buffer/Buffer.html[Buffer]`.

If `send` is used (so not `publish`), and when the Camel exchange expect a reply (_In Out_ exchange), the Vert.x
code expect as reply to the sent message. When the reply arrives it is propagated to the exchange:

[source,kotlin]
----
Code not translatable
----

=== Outbound mapping

Outbound mapping associates an event bus address to a Camel endpoint. Messages received on this event bus address
are transformed to Camel messages and sent to the endpoint.

[source,kotlin]
----
var endpoint = camel.getEndpoint("stream:out")

io.vertx.camel.CamelBridge.create(vertx, io.vertx.camel.CamelBridgeOptions(camel).addOutboundMapping(io.vertx.camel.OutboundMapping.fromVertx("eventbus-address").toCamel("stream:out")).addOutboundMapping(io.vertx.camel.OutboundMapping.fromVertx("eventbus-address").toCamel(endpoint)).addOutboundMapping(io.vertx.camel.OutboundMapping.fromVertx("eventbus-address").toCamel(endpoint).withoutHeadersCopy()).addOutboundMapping(io.vertx.camel.OutboundMapping.fromVertx("eventbus-address").toCamel(endpoint)))

----

The snippet above shows different ways to configure an outbound mapping.

You can connect your outbound mapping to a Camel route:

[source,kotlin]
----
camel.addRoutes(org.apache.camel.builder.RouteBuilder())

var bridge = io.vertx.camel.CamelBridge.create(vertx, io.vertx.camel.CamelBridgeOptions(camel).addOutboundMapping(io.vertx.camel.OutboundMapping.fromVertx("test").toCamel("direct:start")))

camel.start()
bridge.start()


vertx.eventBus().send<Any>("test", "hello", { reply ->
  // Reply from the route (here it's "OK")
})

----

If when you send the message on the event bus you register a reply handler, it configures the Camel exchange to
expect a response (it uses the request-reply pattern of the EIP). The response is passed in the reply body. If the
route fails, you get a reply failure (recipient failure), with the message as cause:

[source,kotlin]
----
camel.addRoutes(org.apache.camel.builder.RouteBuilder())

var bridge = io.vertx.camel.CamelBridge.create(vertx, io.vertx.camel.CamelBridgeOptions(camel).addOutboundMapping(io.vertx.camel.OutboundMapping.fromVertx("camel-route").toCamel("direct:my-route")))

camel.start()
bridge.start()

vertx.eventBus().send<Any>("camel-route", "hello", { reply ->
  if (reply.succeeded()) {
    var theResponse = reply.result().body()
  } else {
    var theCause = reply.cause()
  }
})

----

If the processing you apply is blocking, you **must** set _blocking_ to `true`. This avoid executing the
processing on the event loop thread:

[source,kotlin]
----
camel.addRoutes(org.apache.camel.builder.RouteBuilder())

var bridge = io.vertx.camel.CamelBridge.create(vertx, io.vertx.camel.CamelBridgeOptions(camel).addOutboundMapping(io.vertx.camel.OutboundMapping.fromVertx("camel-route").toCamel("direct:my-route").setBlocking(true)))

camel.start()
bridge.start()

vertx.eventBus().send<Any>("camel-route", "hello", { reply ->
  if (reply.succeeded()) {
    var theResponse = reply.result().body()
  } else {
    var theCause = reply.cause()
  }
})

----

By default it uses the default worker thread pool, this is customizable using the
`link:../../apidocs/io/vertx/camel/OutboundMapping.html#setWorkerExecutor-io.vertx.core.WorkerExecutor-[setWorkerExecutor]` method.

== Stopping the bridge

Don't forget to stop the bridge using the `stop` method. The `stop` method is asynchronous. You can use
`link:../../apidocs/io/vertx/camel/CamelBridge.html#stop-io.vertx.core.Handler-[stop]` to be notified when the bridge has been stopped.

